pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'MinecraftFinders'

include 'finder-core'
include 'geode-finder'
include 'trial-spawner-finder'
include 'minecraft-1.21.1-runtime'
