package cn.trialfinder.cuda;

import cn.trialfinder.accel.Accelerator;
import cn.trialfinder.accel.CpuAccelerator;
import cn.trialfinder.model.BlockPoint;
import jcuda.Pointer;
import jcuda.driver.CUcontext;
import jcuda.driver.CUdevice;
import jcuda.driver.CUdeviceptr;
import jcuda.driver.CUfunction;
import jcuda.driver.CUmodule;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static jcuda.driver.JCudaDriver.cuCtxCreate;
import static jcuda.driver.JCudaDriver.cuCtxDestroy;
import static jcuda.driver.JCudaDriver.cuDeviceComputeCapability;
import static jcuda.driver.JCudaDriver.cuDeviceGet;
import static jcuda.driver.JCudaDriver.cuDeviceGetName;
import static jcuda.driver.JCudaDriver.cuInit;
import static jcuda.driver.JCudaDriver.cuLaunchKernel;
import static jcuda.driver.JCudaDriver.cuMemAlloc;
import static jcuda.driver.JCudaDriver.cuMemcpyDtoH;
import static jcuda.driver.JCudaDriver.cuMemcpyHtoD;
import static jcuda.driver.JCudaDriver.cuMemFree;
import static jcuda.driver.JCudaDriver.cuMemsetD32;
import static jcuda.driver.JCudaDriver.cuModuleGetFunction;
import static jcuda.driver.JCudaDriver.cuModuleLoadData;
import static jcuda.driver.JCudaDriver.setExceptionsEnabled;

/**
 * CUDA implementation of {@link Accelerator} using the JCuda 12.x driver API.
 *
 * <p>Kernels are loaded from a precompiled cubin bundled in the jar
 * ({@code /cuda/trial_finder_<sm>.cubin}, generated by {@code ./gradlew compileCubin}) matched to
 * the GPU's compute capability, so no CUDA Toolkit is required at runtime. When no matching cubin
 * is bundled (or it fails to load) the kernels are compiled at runtime from the embedded
 * {@code /cuda/trial_finder_kernels.cu} resource via NVRTC + ptxas as a fallback. Any
 * initialisation or launch failure is caught by the CLI and the accelerator degrades to
 * {@link CpuAccelerator}.
 */
public final class GpuAccelerator implements Accelerator {

    private static final int BLOCK = 256;
    /** A-flow regions per launch; the kernel is grid-stride so larger batches amortise launch sync. */
    private static final long BATCH_LIMIT = 16_000_000L;
    private static final int DENSITY_CELL_LIMIT = 10_000_000;
    /** Density scoring accepts far larger batches than A-flow enumeration (covers e.g. a 1M-radius search). */
    private static final long DENSITY_BATCH_LIMIT = 64_000_000L;

    private final CpuAccelerator cpu = new CpuAccelerator();
    private final CUcontext context;
    private final CUmodule module;
    private final CUfunction fGenerateChunks;
    private final CUfunction fCellCount;
    private final CUfunction fScatter;
    private final CUfunction fCount;
    private final CUfunction fGridAggregate;
    private final CUfunction fGridCount;
    private final CUfunction fGridCollect;
    private final String deviceName;
    private final int deviceMajor;
    private final int deviceMinor;
    private final String cubinArch;

    // Reusable A-flow buffers. Allocating/freeing large CUDA device buffers (e.g. 108MB for a 1M
    // radius) on Windows takes hundreds of ms per call, so they are kept across findChunks calls
    // and grown only when needed.
    private CUdeviceptr aFlowOutPtr;
    private int aFlowOutCapacity;
    private CUdeviceptr aFlowCountPtr;
    // Reusable density/grid buffers for the GPU-direct grid prefilter (grown on demand).
    private CUdeviceptr dCellCountPtr;
    private int dCellCountCap;
    private CUdeviceptr dCellStartPtr;
    private int dCellStartCap;
    private CUdeviceptr dCellCursorPtr;
    private int dCellCursorCap;
    private CUdeviceptr dCellPointsPtr;
    private int dCellPointsCap;
    private CUdeviceptr dScoresPtr;
    private int dScoresCap;
    private CUdeviceptr dGridScoresPtr;
    private int dGridScoresCap;
    private CUdeviceptr dGridCountsPtr;
    private int dGridCountsCap;

    private GpuAccelerator(CUcontext context, CUmodule module,
                           CUfunction fGenerateChunks, CUfunction fCellCount,
                           CUfunction fScatter, CUfunction fCount, CUfunction fGridAggregate,
                           CUfunction fGridCount, CUfunction fGridCollect,
                           String deviceName, int deviceMajor, int deviceMinor, String cubinArch) {
        this.context = context;
        this.module = module;
        this.fGenerateChunks = fGenerateChunks;
        this.fCellCount = fCellCount;
        this.fScatter = fScatter;
        this.fCount = fCount;
        this.fGridAggregate = fGridAggregate;
        this.fGridCount = fGridCount;
        this.fGridCollect = fGridCollect;
        this.deviceName = deviceName;
        this.deviceMajor = deviceMajor;
        this.deviceMinor = deviceMinor;
        this.cubinArch = cubinArch;
    }

    /** Initialises CUDA, compiles the kernels and returns an accelerator, or throws. */
    public static GpuAccelerator create() {
        long t0 = System.nanoTime();
        setExceptionsEnabled(true);
        cuInit(0);
        CUdevice device = new CUdevice();
        cuDeviceGet(device, 0);
        byte[] nameBuf = new byte[256];
        cuDeviceGetName(nameBuf, nameBuf.length, device);
        String name = new String(nameBuf, StandardCharsets.UTF_8).trim();
        int[] major = new int[1];
        int[] minor = new int[1];
        cuDeviceComputeCapability(major, minor, device);
        CUcontext context = new CUcontext();
        cuCtxCreate(context, 0, device);
        long tInit = System.nanoTime();
        System.out.printf("[timing] CUDA init (cuInit/device/context)  %.1f ms%n", (tInit - t0) / 1e6);
        try {
            String arch = "sm_" + major[0] + minor[0];
            // Prefer a precompiled cubin bundled in the jar; fall back to NVRTC + ptxas when absent.
            CUmodule module = tryLoadPrecompiledCubin(arch, tInit);
            String cubinArch = module != null ? arch : null;
            if (module == null) {
                String source = loadKernelSource();
                long tLoad = System.nanoTime();
                System.out.printf("[timing] kernel source read           %.1f ms%n", (tLoad - tInit) / 1e6);
                // NVRTC (this toolkit) emits PTX 9.3, which the installed driver (CUDA 13.0) rejects
                // with CUDA_ERROR_UNSUPPORTED_PTX_VERSION. Assemble the PTX into an sm_<cc> cubin with
                // ptxas (standalone, no MSVC host compiler needed) and load the cubin instead.
                String ptx = cachedPtx(source, "compute_" + major[0] + minor[0]);
                long tNvrtc = System.nanoTime();
                System.out.printf("[timing] NVRTC .cu -> PTX             %.1f ms%n", (tNvrtc - tLoad) / 1e6);
                byte[] cubin = PtxCompiler.ptxToCubin(ptx, major[0], minor[0]);
                long tPtxas = System.nanoTime();
                System.out.printf("[timing] ptxas PTX -> cubin           %.1f ms%n", (tPtxas - tNvrtc) / 1e6);
                module = new CUmodule();
                cuModuleLoadData(module, cubin);
                long tLoadModule = System.nanoTime();
                System.out.printf("[timing] cuModuleLoadData (cubin)     %.1f ms%n", (tLoadModule - tPtxas) / 1e6);
            }
            CUfunction fA = new CUfunction();
            cuModuleGetFunction(fA, module, "generateChunksKernel");
            CUfunction fB1 = new CUfunction();
            cuModuleGetFunction(fB1, module, "densityCellCount");
            CUfunction fB2 = new CUfunction();
            cuModuleGetFunction(fB2, module, "densityScatter");
            CUfunction fB3 = new CUfunction();
            cuModuleGetFunction(fB3, module, "densityCount");
            CUfunction fGrid = new CUfunction();
            cuModuleGetFunction(fGrid, module, "gridAggregateKernel");
            CUfunction fGridCount = new CUfunction();
            cuModuleGetFunction(fGridCount, module, "generateChunksGridCount");
            CUfunction fGridCollect = new CUfunction();
            cuModuleGetFunction(fGridCollect, module, "generateChunksGridCollect");
            System.out.printf("[timing] GpuAccelerator.create total   %.1f ms%n", (System.nanoTime() - t0) / 1e6);
            return new GpuAccelerator(context, module, fA, fB1, fB2, fB3, fGrid,
                    fGridCount, fGridCollect, name, major[0], minor[0], cubinArch);
        } catch (Throwable t) {
            cuCtxDestroy(context);
            if (t instanceof RuntimeException re) {
                throw re;
            }
            throw new RuntimeException(t);
        }
    }

    public String deviceName() {
        return this.deviceName;
    }

    public int deviceMajor() {
        return this.deviceMajor;
    }

    public int deviceMinor() {
        return this.deviceMinor;
    }

    /** The GPU compute capability as an arch string, e.g. {@code "sm_89"}. */
    public String smArch() {
        return "sm_" + this.deviceMajor + this.deviceMinor;
    }

    /**
     * The arch of the precompiled cubin that was loaded from the classpath, or {@code null} when
     * the module came from the NVRTC + ptxas fallback instead.
     */
    public String precompiledCubinArch() {
        return this.cubinArch;
    }

    @Override
    public boolean isGpu() {
        return true;
    }

    @Override
    public String name() {
        return "gpu:" + this.deviceName + " (sm_" + deviceMajor + deviceMinor + ")";
    }

    // ---------------------------------------------------------------- Accelerator API

    @Override
    public List<BlockPoint> findChunks(long seed, long minX, long maxX, long minZ, long maxZ,
                                       boolean circleFilter, int centerX, int centerZ, long radiusSq) {
        try {
            return findChunksGpu(seed, minX, maxX, minZ, maxZ, circleFilter, centerX, centerZ, radiusSq);
        } catch (Throwable t) {
            return this.cpu.findChunks(seed, minX, maxX, minZ, maxZ, circleFilter, centerX, centerZ, radiusSq);
        }
    }

    @Override
    public boolean[] pruneByDensity(List<BlockPoint> candidates, int clusterRadius, int minStructures) {
        int[] scores = densityScores(candidates, clusterRadius);
        boolean[] keep = new boolean[candidates.size()];
        for (int i = 0; i < keep.length; i++) {
            keep[i] = scores[i] >= minStructures;
        }
        return keep;
    }

    @Override
    public int[] densityScores(List<BlockPoint> candidates, int clusterRadius) {
        try {
            return densityCountsGpu(candidates, clusterRadius);
        } catch (Throwable t) {
            return this.cpu.densityScores(candidates, clusterRadius);
        }
    }

    @Override
    public List<BlockPoint> gridAggregateAndSelect(List<BlockPoint> candidates, int clusterRadius,
                                                   int gridSizeBlocks, int topK) {
        try {
            return gridAggregateAndSelectGpu(candidates, clusterRadius, gridSizeBlocks, topK);
        } catch (Throwable t) {
            return this.cpu.gridAggregateAndSelect(candidates, clusterRadius, gridSizeBlocks, topK);
        }
    }

    /**
     * GPU grid aggregation: reuses {@link #densityScores} (2R neighbour count per candidate),
     * accumulates the total density score per grid cell with {@code gridAggregateKernel}, then
     * selects the top-K cells on the CPU (grid counts are far smaller than candidate counts) and
     * returns the candidates in the selected cells.
     */
    private List<BlockPoint> gridAggregateAndSelectGpu(List<BlockPoint> candidates, int clusterRadius,
                                                       int gridSizeBlocks, int topK) {
        int n = candidates.size();
        if (n == 0 || topK <= 0) {
            return new ArrayList<>();
        }
        int[] scores = densityScores(candidates, clusterRadius);

        int minX = Integer.MAX_VALUE;
        int maxX = Integer.MIN_VALUE;
        int minZ = Integer.MAX_VALUE;
        int maxZ = Integer.MIN_VALUE;
        for (BlockPoint p : candidates) {
            minX = Math.min(minX, p.x());
            maxX = Math.max(maxX, p.x());
            minZ = Math.min(minZ, p.z());
            maxZ = Math.max(maxZ, p.z());
        }
        long spanX = (long) maxX - minX;
        long spanZ = (long) maxZ - minZ;
        int gridDimX = (int) (spanX / gridSizeBlocks + 1);
        int gridDimZ = (int) (spanZ / gridSizeBlocks + 1);
        long cellsLong = (long) gridDimX * gridDimZ;
        if (cellsLong > DENSITY_CELL_LIMIT) {
            // Coarsen the aggregation grid so the cell count stays bounded (a larger cell only
            // merges adjacent cells; selection is still by total density per cell).
            long minCell = (long) Math.ceil(Math.max(spanX, spanZ) / Math.sqrt(DENSITY_CELL_LIMIT));
            int enlarged = Math.max(gridSizeBlocks, (int) Math.min(Integer.MAX_VALUE, minCell));
            gridDimX = (int) (spanX / enlarged + 1);
            gridDimZ = (int) (spanZ / enlarged + 1);
            gridSizeBlocks = enlarged;
        }
        int cells = gridDimX * gridDimZ;

        int[] points = new int[n * 2];
        for (int i = 0; i < n; i++) {
            points[2 * i] = candidates.get(i).x();
            points[2 * i + 1] = candidates.get(i).z();
        }

        CUdeviceptr ptsPtr = new CUdeviceptr();
        cuMemAlloc(ptsPtr, (long) n * 8L);
        CUdeviceptr scoresPtr = new CUdeviceptr();
        cuMemAlloc(scoresPtr, (long) n * 4L);
        CUdeviceptr gridScoresPtr = new CUdeviceptr();
        cuMemAlloc(gridScoresPtr, (long) cells * 4L);
        CUdeviceptr gridCountsPtr = new CUdeviceptr();
        cuMemAlloc(gridCountsPtr, (long) cells * 4L);

        int[] gridScores;
        int[] cellOf = new int[n];
        try {
            cuMemcpyHtoD(ptsPtr, Pointer.to(points), (long) n * 8L);
            cuMemcpyHtoD(scoresPtr, Pointer.to(scores), (long) n * 4L);
            cuMemsetD32(gridScoresPtr, 0, cells);
            cuMemsetD32(gridCountsPtr, 0, cells);

            int grid = (int) Math.ceil(n / (double) BLOCK);
            cuLaunchKernel(fGridAggregate,
                    grid, 1, 1, BLOCK, 1, 1, 0, null,
                    Pointer.to(
                            Pointer.to(new int[]{n}),
                            Pointer.to(ptsPtr),
                            Pointer.to(scoresPtr),
                            Pointer.to(new int[]{minX}),
                            Pointer.to(new int[]{minZ}),
                            Pointer.to(new int[]{gridDimX}),
                            Pointer.to(new int[]{gridDimZ}),
                            Pointer.to(new int[]{gridSizeBlocks}),
                            Pointer.to(gridScoresPtr),
                            Pointer.to(gridCountsPtr)),
                    null);

            gridScores = new int[cells];
            cuMemcpyDtoH(Pointer.to(gridScores), gridScoresPtr, (long) cells * 4L);

            // Compute each candidate's cell on the CPU for the selection pass.
            for (int i = 0; i < n; i++) {
                int gx = (candidates.get(i).x() - minX) / gridSizeBlocks;
                int gz = (candidates.get(i).z() - minZ) / gridSizeBlocks;
                cellOf[i] = gz * gridDimX + gx;
            }
        } finally {
            cuMemFree(ptsPtr);
            cuMemFree(scoresPtr);
            cuMemFree(gridScoresPtr);
            cuMemFree(gridCountsPtr);
        }

        // CPU top-K cell selection (identical to CpuAccelerator).
        List<Integer> occupied = new ArrayList<>();
        for (int cell = 0; cell < cells; cell++) {
            if (gridScores[cell] > 0) {
                occupied.add(cell);
            }
        }
        occupied.sort((a, b) -> {
            int byScore = Integer.compare(gridScores[b], gridScores[a]);
            return byScore != 0 ? byScore : Integer.compare(a, b);
        });
        int keepCells = Math.min(topK, occupied.size());
        java.util.Set<Integer> selected = new java.util.HashSet<>(occupied.subList(0, keepCells));

        List<BlockPoint> retained = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            if (selected.contains(cellOf[i])) {
                retained.add(candidates.get(i));
            }
        }
        retained.sort(BlockPoint::compareTo);
        return retained;
    }

    // ---------------------------------------------------------------- Kernel A

    private List<BlockPoint> findChunksGpu(long seed, long minX, long maxX, long minZ, long maxZ,
                                           boolean circleFilter, int centerX, int centerZ, long radiusSq) {
        int minChunkX = Math.floorDiv(clampToInt(minX), 16);
        int maxChunkX = Math.floorDiv(clampToInt(maxX), 16);
        int minChunkZ = Math.floorDiv(clampToInt(minZ), 16);
        int maxChunkZ = Math.floorDiv(clampToInt(maxZ), 16);
        int spacing = 34;
        int minRegionX = Math.floorDiv(minChunkX, spacing) - 1;
        int maxRegionX = Math.floorDiv(maxChunkX, spacing) + 1;
        int minRegionZ = Math.floorDiv(minChunkZ, spacing) - 1;
        int maxRegionZ = Math.floorDiv(maxChunkZ, spacing) + 1;
        int rxCount = maxRegionX - minRegionX + 1;
        long total = (long) rxCount * (maxRegionZ - minRegionZ + 1);

        ArrayList<BlockPoint> result = new ArrayList<>();
        // Count buffer (4 bytes) reused across calls.
        if (this.aFlowCountPtr == null) {
            this.aFlowCountPtr = new CUdeviceptr();
            cuMemAlloc(this.aFlowCountPtr, 4L);
        }
        CUdeviceptr countPtr = this.aFlowCountPtr;
        try {
            long start = 0;
            while (start < total) {
                long end = Math.min(total, start + BATCH_LIMIT);
                int capacity = (int) (end - start);
                // Grow the reused output buffer only when this batch needs more than the largest
                // seen so far — no per-call allocation, and batch-to-batch reuse within a call.
                if (capacity > this.aFlowOutCapacity) {
                    if (this.aFlowOutPtr != null) {
                        cuMemFree(this.aFlowOutPtr);
                    }
                    this.aFlowOutPtr = new CUdeviceptr();
                    cuMemAlloc(this.aFlowOutPtr, (long) capacity * 8L);
                    this.aFlowOutCapacity = capacity;
                }
                CUdeviceptr outPtr = this.aFlowOutPtr;
                cuMemsetD32(countPtr, 0, 1);
                int grid = (int) Math.ceil(capacity / (double) BLOCK);
                long tLaunch = System.nanoTime();
                cuLaunchKernel(fGenerateChunks,
                        grid, 1, 1, BLOCK, 1, 1, 0, null,
                        Pointer.to(
                                Pointer.to(new long[]{seed}),
                                Pointer.to(new int[]{minRegionX}),
                                Pointer.to(new int[]{minRegionZ}),
                                Pointer.to(new int[]{rxCount}),
                                Pointer.to(new long[]{start}),
                                Pointer.to(new long[]{end}),
                                Pointer.to(new int[]{clampToInt(minX)}),
                                Pointer.to(new int[]{clampToInt(maxX)}),
                                Pointer.to(new int[]{clampToInt(minZ)}),
                                Pointer.to(new int[]{clampToInt(maxZ)}),
                                Pointer.to(new int[]{circleFilter ? 1 : 0}),
                                Pointer.to(new int[]{centerX}),
                                Pointer.to(new int[]{centerZ}),
                                Pointer.to(new long[]{radiusSq}),
                                Pointer.to(outPtr),
                                Pointer.to(countPtr),
                                Pointer.to(new int[]{capacity})),
                        null);
                int[] count = new int[1];
                cuMemcpyDtoH(Pointer.to(count), countPtr, 4L);
                long tCount = System.nanoTime();
                int n = count[0];
                long tObj = System.nanoTime();
                if (n > 0) {
                    // Pre-size so the ArrayList never reallocates; the per-batch count is known.
                    result.ensureCapacity(result.size() + n);
                    int[] data = new int[n * 2];
                    cuMemcpyDtoH(Pointer.to(data), outPtr, n * 8L);
                    for (int i = 0; i < n; i++) {
                        result.add(new BlockPoint(data[2 * i], data[2 * i + 1]));
                    }
                }
                if (System.getProperty("trialfinder.trace.aflow") != null) {
                    System.out.printf("[aflow] cap=%d grid=%d n=%d kernel+countD2H=%.1fms obj=%.1fms%n",
                            capacity, grid, n, (tCount - tLaunch) / 1e6, (System.nanoTime() - tObj) / 1e6);
                }
                start = end;
            }
        } finally {
            // count/out buffers are intentionally kept for reuse across calls (no free here).
        }
        result.sort(BlockPoint::compareTo);
        return result;
    }

    // ---------------------------------------------------------------- GPU-direct grid prefilter (A-flow → grid)

    /**
     * GPU-direct grid prefilter for huge single-region searches. Enumerates candidate chambers
     * entirely on the GPU, computes their density scores on the GPU, aggregates those scores into
     * grid cells, selects the top-K cells by total density (the same criterion as the host
     * {@link #gridAggregateAndSelect}), and returns only the candidates inside the selected cells.
     *
     * <p>This reproduces the host grid-prefilter result while avoiding constructing millions of
     * {@link BlockPoint} objects in Java (the real A-flow bottleneck for large radii — the
     * enumerate kernel itself finishes in ~2ms; host object allocation + GC was the slowdown).
     *
     * @return candidates inside the top-K grid cells (sorted, de-duplicated)
     */
    public List<BlockPoint> findChunksGridPrefiltered(
            long seed, long minX, long maxX, long minZ, long maxZ,
            boolean circleFilter, int centerX, int centerZ, long radiusSq,
            int clusterRadius, int gridSize, int topK) {
        int minChunkX = Math.floorDiv(clampToInt(minX), 16);
        int maxChunkX = Math.floorDiv(clampToInt(maxX), 16);
        int minChunkZ = Math.floorDiv(clampToInt(minZ), 16);
        int maxChunkZ = Math.floorDiv(clampToInt(maxZ), 16);
        int spacing = 34;
        int minRegionX = Math.floorDiv(minChunkX, spacing) - 1;
        int maxRegionX = Math.floorDiv(maxChunkX, spacing) + 1;
        int minRegionZ = Math.floorDiv(minChunkZ, spacing) - 1;
        int maxRegionZ = Math.floorDiv(maxChunkZ, spacing) + 1;
        int rxCount = maxRegionX - minRegionX + 1;
        long total = (long) rxCount * (maxRegionZ - minRegionZ + 1);
        if (total <= 0) {
            return List.of();
        }

        // Pass 1: enumerate candidates straight into the reused device buffer (no host round-trip).
        int n = enumerateToGpu(seed, minRegionX, minRegionZ, rxCount, total,
                clampToInt(minX), clampToInt(maxX), clampToInt(minZ), clampToInt(maxZ),
                circleFilter, centerX, centerZ, radiusSq);
        if (n == 0) {
            return List.of();
        }
        if (n > DENSITY_BATCH_LIMIT) {
            throw new IllegalStateException("density batch too large: " + n);
        }
        CUdeviceptr pointsPtr = this.aFlowOutPtr; // int2[n] candidates from pass 1

        // Compute the candidate extent on the host (a plain int[] scan, NOT BlockPoint objects) so
        // the density and aggregation grids use the same origin as the host gridAggregateAndSelect —
        // otherwise cell boundaries shift and the top-K selection differs.
        int[] hostPoints = new int[n * 2];
        cuMemcpyDtoH(Pointer.to(hostPoints), pointsPtr, (long) n * 8L);
        int cMinX = Integer.MAX_VALUE, cMaxX = Integer.MIN_VALUE;
        int cMinZ = Integer.MAX_VALUE, cMaxZ = Integer.MIN_VALUE;
        for (int i = 0; i < n; i++) {
            int x = hostPoints[2 * i];
            int z = hostPoints[2 * i + 1];
            if (x < cMinX) cMinX = x;
            if (x > cMaxX) cMaxX = x;
            if (z < cMinZ) cMinZ = z;
            if (z > cMaxZ) cMaxZ = z;
        }
        int gridOriginX = cMinX;
        int gridOriginZ = cMinZ;
        long spanX = (long) cMaxX - cMinX;
        long spanZ = (long) cMaxZ - cMinZ;

        // Pass 2: density scores on the GPU (2R neighbour count), reusing the host density pipeline
        // but with the candidate buffer already on device.
        int densityCell = Math.max(1, clusterRadius * 2);
        long radius2Sq = (long) densityCell * densityCell;
        long dCellsLong = (spanX / densityCell + 1) * (spanZ / densityCell + 1);
        if (dCellsLong > DENSITY_CELL_LIMIT) {
            long minCell = (long) Math.ceil(Math.max(spanX, spanZ) / Math.sqrt(DENSITY_CELL_LIMIT));
            densityCell = Math.max(densityCell, (int) Math.min(Integer.MAX_VALUE, minCell));
        }
        int dDimX = (int) (spanX / densityCell + 1);
        int dDimZ = (int) (spanZ / densityCell + 1);
        int dCells = dDimX * dDimZ;

        // Reuse device buffers across tiles (allocating ~200MB per tile on Windows is very slow).
        ensureBuffer(dCells * 4L, () -> this.dCellCountPtr, v -> this.dCellCountPtr = v,
                () -> this.dCellCountCap, c -> this.dCellCountCap = c);
        ensureBuffer((long) (dCells + 1) * 4L, () -> this.dCellStartPtr, v -> this.dCellStartPtr = v,
                () -> this.dCellStartCap, c -> this.dCellStartCap = c);
        ensureBuffer(dCells * 4L, () -> this.dCellCursorPtr, v -> this.dCellCursorPtr = v,
                () -> this.dCellCursorCap, c -> this.dCellCursorCap = c);
        ensureBuffer((long) n * 4L, () -> this.dCellPointsPtr, v -> this.dCellPointsPtr = v,
                () -> this.dCellPointsCap, c -> this.dCellPointsCap = c);
        ensureBuffer((long) n * 4L, () -> this.dScoresPtr, v -> this.dScoresPtr = v,
                () -> this.dScoresCap, c -> this.dScoresCap = c);
        CUdeviceptr dCellCount = this.dCellCountPtr;
        CUdeviceptr dCellStart = this.dCellStartPtr;
        CUdeviceptr dCellCursor = this.dCellCursorPtr;
        CUdeviceptr dCellPoints = this.dCellPointsPtr;
        CUdeviceptr scoresPtr = this.dScoresPtr;

        // Pass 3: aggregate density scores into grid cells (the gridSize cell, not the density cell).
        long gCellsLong = (spanX / gridSize + 1) * (spanZ / gridSize + 1);
        if (gCellsLong > DENSITY_CELL_LIMIT) {
            long minCell = (long) Math.ceil(Math.max(spanX, spanZ) / Math.sqrt(DENSITY_CELL_LIMIT));
            int enlarged = Math.max(gridSize, (int) Math.min(Integer.MAX_VALUE, minCell));
            gridSize = enlarged;
        }
        int gDimX = (int) (spanX / gridSize + 1);
        int gDimZ = (int) (spanZ / gridSize + 1);
        int gCells = gDimX * gDimZ;

        ensureBuffer((long) gCells * 4L, () -> this.dGridScoresPtr, v -> this.dGridScoresPtr = v,
                () -> this.dGridScoresCap, c -> this.dGridScoresCap = c);
        ensureBuffer((long) gCells * 4L, () -> this.dGridCountsPtr, v -> this.dGridCountsPtr = v,
                () -> this.dGridCountsCap, c -> this.dGridCountsCap = c);
        CUdeviceptr gridScoresPtr = this.dGridScoresPtr;
        CUdeviceptr gridCountsPtr = this.dGridCountsPtr;

        ArrayList<BlockPoint> result = new ArrayList<>();
        try {
            // --- density (2R spatial hash) ---
            int grid = (int) Math.ceil(n / (double) BLOCK);
            cuMemsetD32(dCellCount, 0, dCells);
            cuMemsetD32(dCellCursor, 0, dCells);
            cuLaunchKernel(fCellCount, grid, 1, 1, BLOCK, 1, 1, 0, null,
                    Pointer.to(
                            Pointer.to(new int[]{n}), Pointer.to(pointsPtr),
                            Pointer.to(new int[]{gridOriginX}), Pointer.to(new int[]{gridOriginZ}),
                            Pointer.to(new int[]{dDimX}), Pointer.to(new int[]{dDimZ}),
                            Pointer.to(new int[]{densityCell}), Pointer.to(dCellCount)),
                    null);
            int[] dCount = new int[dCells];
            cuMemcpyDtoH(Pointer.to(dCount), dCellCount, (long) dCells * 4L);
            int[] dStart = new int[dCells + 1];
            for (int i = 0; i < dCells; i++) {
                dStart[i + 1] = dStart[i] + dCount[i];
            }
            cuMemcpyHtoD(dCellStart, Pointer.to(dStart), (long) (dCells + 1) * 4L);
            cuLaunchKernel(fScatter, grid, 1, 1, BLOCK, 1, 1, 0, null,
                    Pointer.to(
                            Pointer.to(new int[]{n}), Pointer.to(pointsPtr),
                            Pointer.to(new int[]{gridOriginX}), Pointer.to(new int[]{gridOriginZ}),
                            Pointer.to(new int[]{dDimX}), Pointer.to(new int[]{dDimZ}),
                            Pointer.to(new int[]{densityCell}), Pointer.to(dCellStart),
                            Pointer.to(dCellCursor), Pointer.to(dCellPoints)),
                    null);
            cuLaunchKernel(fCount, grid, 1, 1, BLOCK, 1, 1, 0, null,
                    Pointer.to(
                            Pointer.to(new int[]{n}), Pointer.to(pointsPtr),
                            Pointer.to(dCellStart), Pointer.to(dCellPoints),
                            Pointer.to(new int[]{gridOriginX}), Pointer.to(new int[]{gridOriginZ}),
                            Pointer.to(new int[]{dDimX}), Pointer.to(new int[]{dDimZ}),
                            Pointer.to(new int[]{densityCell}), Pointer.to(new long[]{radius2Sq}),
                            Pointer.to(scoresPtr)),
                    null);

            // --- grid aggregate (gridSize cells, density-weighted) ---
            if (System.getProperty("trialfinder.trace.aflow") != null) {
                System.out.printf("[gd] n=%d dCells=%d gCells=%d gridDim=%dx%d gridSize=%d%n",
                        n, dCells, gCells, gDimX, gDimZ, gridSize);
            }
            cuMemsetD32(gridScoresPtr, 0, gCells);
            cuMemsetD32(gridCountsPtr, 0, gCells);
            cuLaunchKernel(fGridAggregate, grid, 1, 1, BLOCK, 1, 1, 0, null,
                    Pointer.to(
                            Pointer.to(new int[]{n}), Pointer.to(pointsPtr), Pointer.to(scoresPtr),
                            Pointer.to(new int[]{gridOriginX}), Pointer.to(new int[]{gridOriginZ}),
                            Pointer.to(new int[]{gDimX}), Pointer.to(new int[]{gDimZ}),
                            Pointer.to(new int[]{gridSize}),
                            Pointer.to(gridScoresPtr), Pointer.to(gridCountsPtr)),
                    null);

            int[] gridScores = new int[gCells];
            cuMemcpyDtoH(Pointer.to(gridScores), gridScoresPtr, (long) gCells * 4L);

            // --- CPU top-K cell selection (density-weighted, ties by cell index) ---
            Integer[] sortedCells = new Integer[gCells];
            for (int c = 0; c < gCells; c++) {
                sortedCells[c] = c;
            }
            int[] gs = gridScores;
            java.util.Arrays.sort(sortedCells, (a, b) -> {
                int by = Integer.compare(gs[b], gs[a]);
                return by != 0 ? by : Integer.compare(a, b);
            });
            int keep = Math.min(topK, gCells);
            byte[] selected = new byte[gCells];
            for (int i = 0; i < keep; i++) {
                if (gs[sortedCells[i]] > 0) {
                    selected[sortedCells[i]] = 1;
                }
            }

            // --- collect candidates in selected grid cells (re-enumerate) ---
            CUdeviceptr selectedPtr = new CUdeviceptr();
            cuMemAlloc(selectedPtr, (long) gCells);
            cuMemcpyHtoD(selectedPtr, Pointer.to(selected), (long) gCells);
            CUdeviceptr outPtr = new CUdeviceptr();
            cuMemAlloc(outPtr, (long) gCells * 8L); // upper bound: one candidate per cell
            CUdeviceptr countPtr = new CUdeviceptr();
            cuMemAlloc(countPtr, 4L);
            try {
                cuMemsetD32(countPtr, 0, 1);
                long start = 0;
                while (start < total) {
                    long end = Math.min(total, start + BATCH_LIMIT);
                    int capacity = (int) (end - start);
                    int g = (int) Math.ceil(capacity / (double) BLOCK);
                    cuLaunchKernel(fGridCollect, g, 1, 1, BLOCK, 1, 1, 0, null,
                            Pointer.to(
                                    Pointer.to(new long[]{seed}),
                                    Pointer.to(new int[]{minRegionX}), Pointer.to(new int[]{minRegionZ}),
                                    Pointer.to(new int[]{rxCount}),
                                    Pointer.to(new long[]{start}), Pointer.to(new long[]{end}),
                                    Pointer.to(new int[]{clampToInt(minX)}), Pointer.to(new int[]{clampToInt(maxX)}),
                                    Pointer.to(new int[]{clampToInt(minZ)}), Pointer.to(new int[]{clampToInt(maxZ)}),
                                    Pointer.to(new int[]{circleFilter ? 1 : 0}),
                                    Pointer.to(new int[]{centerX}), Pointer.to(new int[]{centerZ}),
                                    Pointer.to(new long[]{radiusSq}),
                                    Pointer.to(new int[]{gridOriginX}), Pointer.to(new int[]{gridOriginZ}),
                                    Pointer.to(new int[]{gDimX}), Pointer.to(new int[]{gDimZ}),
                                    Pointer.to(new int[]{gridSize}),
                                    Pointer.to(selectedPtr), Pointer.to(outPtr), Pointer.to(countPtr),
                                    Pointer.to(new int[]{capacity})),
                            null);
                    start = end;
                }
                int[] count = new int[1];
                cuMemcpyDtoH(Pointer.to(count), countPtr, 4L);
                int cnt = count[0];
                if (cnt > 0) {
                    int[] data = new int[cnt * 2];
                    cuMemcpyDtoH(Pointer.to(data), outPtr, cnt * 8L);
                    result.ensureCapacity(cnt);
                    for (int i = 0; i < cnt; i++) {
                        result.add(new BlockPoint(data[2 * i], data[2 * i + 1]));
                    }
                }
            } finally {
                cuMemFree(selectedPtr);
                cuMemFree(outPtr);
                cuMemFree(countPtr);
            }
        } finally {
            // Reused device buffers (dCell*, scores, grid*) are intentionally kept across calls.
        }
        result.sort(BlockPoint::compareTo);
        return result;
    }

    /**
     * Enumerates candidate chambers into the reused {@link #aFlowOutPtr} device buffer, returning
     * the number produced. The buffer is sized to the largest batch so the returned candidate list
     * lives entirely on the GPU (no host object allocation).
     */
    private int enumerateToGpu(long seed, int minRegionX, int minRegionZ, int rxCount, long total,
                               int minX, int maxX, int minZ, int maxZ,
                               boolean circleFilter, int centerX, int centerZ, long radiusSq) {
        if (this.aFlowCountPtr == null) {
            this.aFlowCountPtr = new CUdeviceptr();
            cuMemAlloc(this.aFlowCountPtr, 4L);
        }
        CUdeviceptr countPtr = this.aFlowCountPtr;
        int totalN = 0;
        long start = 0;
        while (start < total) {
            long end = Math.min(total, start + BATCH_LIMIT);
            int capacity = (int) (end - start);
            if (capacity > this.aFlowOutCapacity) {
                if (this.aFlowOutPtr != null) {
                    cuMemFree(this.aFlowOutPtr);
                }
                this.aFlowOutPtr = new CUdeviceptr();
                cuMemAlloc(this.aFlowOutPtr, (long) capacity * 8L);
                this.aFlowOutCapacity = capacity;
            }
            CUdeviceptr outPtr = this.aFlowOutPtr;
            cuMemsetD32(countPtr, 0, 1);
            int grid = (int) Math.ceil(capacity / (double) BLOCK);
            cuLaunchKernel(fGenerateChunks, grid, 1, 1, BLOCK, 1, 1, 0, null,
                    Pointer.to(
                            Pointer.to(new long[]{seed}),
                            Pointer.to(new int[]{minRegionX}), Pointer.to(new int[]{minRegionZ}),
                            Pointer.to(new int[]{rxCount}),
                            Pointer.to(new long[]{start}), Pointer.to(new long[]{end}),
                            Pointer.to(new int[]{minX}), Pointer.to(new int[]{maxX}),
                            Pointer.to(new int[]{minZ}), Pointer.to(new int[]{maxZ}),
                            Pointer.to(new int[]{circleFilter ? 1 : 0}),
                            Pointer.to(new int[]{centerX}), Pointer.to(new int[]{centerZ}),
                            Pointer.to(new long[]{radiusSq}),
                            Pointer.to(outPtr), Pointer.to(countPtr),
                            Pointer.to(new int[]{capacity})),
                    null);
            int[] count = new int[1];
            cuMemcpyDtoH(Pointer.to(count), countPtr, 4L);
            totalN += count[0];
            start = end;
        }
        return totalN;
    }

    /** Grows a reused device buffer to at least {@code bytes}; no-op when already large enough. */
    private void ensureBuffer(long bytes,
                              java.util.function.Supplier<CUdeviceptr> getter,
                              java.util.function.Consumer<CUdeviceptr> setter,
                              java.util.function.IntSupplier capGetter,
                              java.util.function.IntConsumer capSetter) {
        CUdeviceptr ptr = getter.get();
        if (ptr != null && bytes <= capGetter.getAsInt()) {
            return;
        }
        if (ptr != null) {
            cuMemFree(ptr);
        }
        CUdeviceptr fresh = new CUdeviceptr();
        cuMemAlloc(fresh, bytes);
        setter.accept(fresh);
        capSetter.accept((int) bytes);
    }

    // ---------------------------------------------------------------- Kernel B

    private int[] densityCountsGpu(List<BlockPoint> candidates, int clusterRadius) {
        int n = candidates.size();
        int[] counts = new int[n];
        if (n == 0) {
            return counts;
        }
        if (n > DENSITY_BATCH_LIMIT) {
            throw new IllegalStateException("density batch too large: " + n);
        }
        // Density neighbour criterion radius (2R) is fixed; the spatial hash cell is enlarged when
        // the grid would exceed DENSITY_CELL_LIMIT. Enlarging the cell is lossless: a coarser grid
        // still covers every neighbour within 2R in the 3x3 neighbourhood, so counts are unchanged.
        int cellSize = Math.max(1, clusterRadius * 2);
        long radiusSq = (long) cellSize * cellSize;

        int minX = Integer.MAX_VALUE;
        int maxX = Integer.MIN_VALUE;
        int minZ = Integer.MAX_VALUE;
        int maxZ = Integer.MIN_VALUE;
        for (BlockPoint p : candidates) {
            minX = Math.min(minX, p.x());
            maxX = Math.max(maxX, p.x());
            minZ = Math.min(minZ, p.z());
            maxZ = Math.max(maxZ, p.z());
        }
        long spanX = (long) maxX - minX;
        long spanZ = (long) maxZ - minZ;
        long cells = (spanX / cellSize + 1) * (spanZ / cellSize + 1);
        if (cells > DENSITY_CELL_LIMIT) {
            long minCell = (long) Math.ceil(Math.max(spanX, spanZ) / Math.sqrt(DENSITY_CELL_LIMIT));
            int enlarged = Math.max(cellSize, (int) Math.min(Integer.MAX_VALUE, minCell));
            if (System.getProperty("trialfinder.debug.cells") != null) {
                System.out.printf("[density] cells %,d > limit, cellSize %d -> %d%n", cells, cellSize, enlarged);
            }
            cellSize = enlarged;
        }
        int gridDimX = (int) (spanX / cellSize + 1);
        int gridDimZ = (int) (spanZ / cellSize + 1);
        int cellsUsed = gridDimX * gridDimZ;

        int[] points = new int[n * 2];
        for (int i = 0; i < n; i++) {
            points[2 * i] = candidates.get(i).x();
            points[2 * i + 1] = candidates.get(i).z();
        }

        CUdeviceptr ptsPtr = new CUdeviceptr();
        cuMemAlloc(ptsPtr, (long) n * 8L);
        CUdeviceptr cellCountPtr = new CUdeviceptr();
        cuMemAlloc(cellCountPtr, (long) cellsUsed * 4L);
        CUdeviceptr cellStartPtr = new CUdeviceptr();
        cuMemAlloc(cellStartPtr, (long) (cellsUsed + 1) * 4L);
        CUdeviceptr cellCursorPtr = new CUdeviceptr();
        cuMemAlloc(cellCursorPtr, (long) cellsUsed * 4L);
        CUdeviceptr cellPointsPtr = new CUdeviceptr();
        cuMemAlloc(cellPointsPtr, (long) n * 4L);
        CUdeviceptr countsPtr = new CUdeviceptr();
        cuMemAlloc(countsPtr, (long) n * 4L);

        try {
            cuMemcpyHtoD(ptsPtr, Pointer.to(points), (long) n * 8L);
            cuMemsetD32(cellCountPtr, 0, cellsUsed);
            cuMemsetD32(cellCursorPtr, 0, cellsUsed);

            int grid = (int) Math.ceil(n / (double) BLOCK);

            cuLaunchKernel(fCellCount,
                    grid, 1, 1, BLOCK, 1, 1, 0, null,
                    Pointer.to(
                            Pointer.to(new int[]{n}),
                            Pointer.to(ptsPtr),
                            Pointer.to(new int[]{minX}),
                            Pointer.to(new int[]{minZ}),
                            Pointer.to(new int[]{gridDimX}),
                            Pointer.to(new int[]{gridDimZ}),
                            Pointer.to(new int[]{cellSize}),
                            Pointer.to(cellCountPtr)),
                    null);

            int[] cellCount = new int[cellsUsed];
            cuMemcpyDtoH(Pointer.to(cellCount), cellCountPtr, (long) cellsUsed * 4L);
            int[] cellStart = new int[cellsUsed + 1];
            for (int i = 0; i < cellsUsed; i++) {
                cellStart[i + 1] = cellStart[i] + cellCount[i];
            }
            cuMemcpyHtoD(cellStartPtr, Pointer.to(cellStart), (long) (cellsUsed + 1) * 4L);

            cuLaunchKernel(fScatter,
                    grid, 1, 1, BLOCK, 1, 1, 0, null,
                    Pointer.to(
                            Pointer.to(new int[]{n}),
                            Pointer.to(ptsPtr),
                            Pointer.to(new int[]{minX}),
                            Pointer.to(new int[]{minZ}),
                            Pointer.to(new int[]{gridDimX}),
                            Pointer.to(new int[]{gridDimZ}),
                            Pointer.to(new int[]{cellSize}),
                            Pointer.to(cellStartPtr),
                            Pointer.to(cellCursorPtr),
                            Pointer.to(cellPointsPtr)),
                    null);

            cuLaunchKernel(fCount,
                    grid, 1, 1, BLOCK, 1, 1, 0, null,
                    Pointer.to(
                            Pointer.to(new int[]{n}),
                            Pointer.to(ptsPtr),
                            Pointer.to(cellStartPtr),
                            Pointer.to(cellPointsPtr),
                            Pointer.to(new int[]{minX}),
                            Pointer.to(new int[]{minZ}),
                            Pointer.to(new int[]{gridDimX}),
                            Pointer.to(new int[]{gridDimZ}),
                            Pointer.to(new int[]{cellSize}),
                            Pointer.to(new long[]{radiusSq}),
                            Pointer.to(countsPtr)),
                    null);

            cuMemcpyDtoH(Pointer.to(counts), countsPtr, (long) n * 4L);
        } finally {
            cuMemFree(ptsPtr);
            cuMemFree(cellCountPtr);
            cuMemFree(cellStartPtr);
            cuMemFree(cellCursorPtr);
            cuMemFree(cellPointsPtr);
            cuMemFree(countsPtr);
        }
        return counts;
    }

    // ---------------------------------------------------------------- precompiled cubin loading

    /**
     * Attempts to load a precompiled cubin for {@code arch} (e.g. {@code "sm_89"}) from the
     * classpath ({@code /cuda/trial_finder_<arch>.cubin}, generated by {@code compileCubin}).
     * Returns the loaded module, or {@code null} when no cubin is bundled or it fails to load —
     * the caller then falls back to NVRTC + ptxas.
     */
    private static CUmodule tryLoadPrecompiledCubin(String arch, long tStart) {
        String resource = "/cuda/trial_finder_" + arch + ".cubin";
        try (InputStream in = GpuAccelerator.class.getResourceAsStream(resource)) {
            if (in == null) {
                System.out.println("[DEBUG] no precompiled cubin on classpath for " + arch
                        + " (" + resource + "); using NVRTC + ptxas");
                return null;
            }
            byte[] data = in.readAllBytes();
            CUmodule module = new CUmodule();
            cuModuleLoadData(module, data);
            long tLoaded = System.nanoTime();
            System.out.printf("[DEBUG] loaded precompiled cubin %s (%d bytes) in %.1f ms%n",
                    arch, data.length, (tLoaded - tStart) / 1e6);
            return module;
        } catch (IOException e) {
            System.out.println("[DEBUG] failed to read precompiled cubin " + resource + ": "
                    + e.getMessage() + "; using NVRTC + ptxas");
            return null;
        } catch (Throwable t) {
            // cuModuleLoadData throws when the cubin arch does not match the device; the module
            // is discarded and the NVRTC fallback recompiles for the actual arch.
            System.out.println("[DEBUG] failed to load precompiled cubin " + arch + ": "
                    + t.getClass().getSimpleName() + ": " + t.getMessage() + "; using NVRTC + ptxas");
            return null;
        }
    }

    // ---------------------------------------------------------------- NVRTC + PTX cache

    /** Compiles source→PTX via NVRTC, cached on disk keyed by (source-hash, arch). */
    private static String cachedPtx(String source, String arch) {
        String key = sha256(source + "|" + arch);
        Path cacheDir = Path.of(System.getProperty("trialfinder.ptx.cache",
                System.getProperty("java.io.tmpdir", "/tmp") + "/trialfinder-cubin"));
        Path cached = cacheDir.resolve("kernels-" + key + ".ptx");
        try {
            if (Files.isRegularFile(cached)) {
                return Files.readString(cached, StandardCharsets.UTF_8);
            }
        } catch (IOException e) {
            // fall through to fresh compile
        }
        String ptx = NvrtcCompiler.compile(source, arch);
        try {
            Files.createDirectories(cacheDir);
            Files.writeString(cached, ptx, StandardCharsets.UTF_8);
        } catch (IOException ignored) {
            // best-effort cache write
        }
        return ptx;
    }

    private static String sha256(String text) {
        try {
            byte[] hash = java.security.MessageDigest.getInstance("SHA-256")
                    .digest(text.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder(hash.length * 2);
            for (byte b : hash) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            return Integer.toHexString(text.hashCode());
        }
    }

    private static String loadKernelSource() throws IOException {
        try (InputStream in = GpuAccelerator.class.getResourceAsStream("/cuda/trial_finder_kernels.cu")) {
            if (in == null) {
                throw new IOException("kernel source not found on classpath: /cuda/trial_finder_kernels.cu");
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static int clampToInt(long value) {
        return (int) Math.max(Integer.MIN_VALUE, Math.min(Integer.MAX_VALUE, value));
    }
}
